// Data access seam.
//
// v1: historical measured runs are read from the bundled runs.json
// (generated by scripts/extract_runs.py from the real CSVs).
//
// Later (choice-2 "hosted dashboard"): add fetchLiveRun() here that hits a
// Google-Sheets-backed JSON endpoint (the device already logs to Sheets via
// the Apps Script doGet). The /data page and chart component stay unchanged —
// only this module learns a new source. Keep that bolt-on read-only.

import runsJson from './runs.json'

export interface RunPoint {
  hod: number // continuous hour-of-day (start-day midnight = 0; carries past 24 overnight)
  co2: number
  fan?: number // % duty (Fahey only)
  tempC?: number // indoor temperature, °C (measured; present where logged)
  hum?: number // relative humidity, % (measured; present where logged)
  tempOutC?: number // outdoor temperature, °C (EW run only)
}

export interface RunPhase {
  from: number
  to: number
  label: string
  kind: 'open' | 'closed'
}

export interface Run {
  id: string
  name: string
  tag: string
  framing: string
  takeaway: string
  peak: number // chart max (5-min averaged)
  peakLabel: number // documented absolute peak (single-sample)
  peakNote: string // short qualifier shown next to the peak
  n: number
  hero?: boolean
  showFan?: boolean
  phases?: RunPhase[]
  points: RunPoint[]
}

interface RunsFile {
  order: string[]
  runs: Record<string, Run>
}

const data = runsJson as unknown as RunsFile

export function getRuns(): Run[] {
  return data.order.map((id) => data.runs[id])
}

export function getRun(id: string): Run | undefined {
  return data.runs[id]
}
