[env:esp32c3]
platform = espressif32
board = seeed_xiao_esp32c3
framework = arduino
monitor_speed = 115200
upload_port = COM8
monitor_port = COM8
lib_deps =
    paulstoffregen/OneWire@^2.3.7
    milesburton/DallasTemperature@^3.11.0
