[platformio]
default_envs = esp32dev

[env:esp32dev]
platform = espressif32
board = esp32dev
framework = arduino
monitor_speed = 115200
upload_port = COM6
monitor_port = COM6
build_src_filter = +<main.cpp>
lib_deps =
    https://github.com/Sensirion/arduino-core
    https://github.com/Sensirion/arduino-i2c-scd4x
    paulstoffregen/OneWire@^2.3.7
    milesburton/DallasTemperature@^3.11.0
    adafruit/Adafruit SSD1306@^2.5.7
    adafruit/Adafruit GFX Library@^1.11.9
    https://github.com/me-no-dev/ESPAsyncWebServer
    https://github.com/me-no-dev/AsyncTCP
    bblanchon/ArduinoJson@^7.0.4

[env:sim]
platform = espressif32
board = esp32dev
framework = arduino
monitor_speed = 115200
build_src_filter = +<main_sim.cpp>
lib_deps =
    paulstoffregen/OneWire@^2.3.7
    milesburton/DallasTemperature@^3.11.0
    adafruit/Adafruit SSD1306@^2.5.7
    adafruit/Adafruit GFX Library@^1.11.9
    https://github.com/me-no-dev/ESPAsyncWebServer
    https://github.com/me-no-dev/AsyncTCP
    bblanchon/ArduinoJson@^7.0.4
